# The upstream project is cloned in a parent pipeline

.use-clone:
  pipeline: ${PARENT_PIPELINE}
  job: clone

# A special job for compiling the tinker interface
# By adding "tinker" as a dependency, other jobs can use it

tinker:
  stage: build
  image: ${CI_REGISTRY}/molcas/dockerfiles/gcc-9:latest
  interruptible: true
  variables:
    # A patch to the tinker patch to make it work in low memory conditions
    patch_to_patch: |
                    diff -Nu -x '*~' -x '*.o' 6.3.3/source_orig/sizes.i 6.3.3/source/sizes.i
                    --- 6.3.3/source_orig/sizes.i   2015-04-14 13:58:10.122343730 +0200
                    +++ 6.3.3/source/sizes.i        2015-04-15 13:48:53.796041225 +0200
                    @@ -64,7 +64,7 @@
                           integer maxele,maxamino,maxnuc
                           integer maxbnd,maxang,maxtors
                           integer maxbitor
                    -      parameter (maxatm=100000)
                    +      parameter (maxatm=1000)
                           parameter (maxval=8)
                           parameter (maxgrp=1000)
                           parameter (maxref=10)
  before_script:
    - >
      if ( ! which patch ) ; then apt-get install -y --no-install-recommends patch ; fi
  script:
    # change into the cloned subdirectory if necessary
    - |
      if [ -n "${CLONED_DIR}" ] ; then
        cd ${CLONED_DIR}
      fi
    # Use backup if the tinker website is down
    - >
      sed -i -e 's/wget.*/& || \\/' -e '/wget/a git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/Molcas/Mirrors/Tinker.git ; mv Tinker/${TINKERVERSION}.tar.gz .' Tools/patch2tinker/get_tinker
    # Try to work around https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92318
    - >
      sed -i -e 's/make all/make all || make all || make all || make all || make all || make all || make all || make all || make all || make all/' Tools/patch2tinker/get_tinker
    # Apply the low-memory patch
    - |
      eval `grep TINKERVERSION= Tools/patch2tinker/get_tinker`
      eval `grep PATCH= Tools/patch2tinker/get_tinker`
      echo "${patch_to_patch}" >> Tools/patch2tinker/${PATCH}
    - >
      echo "y" | Tools/patch2tinker/get_tinker
  after_script:
    - |
      mkdir build
      if [ -n "${CLONED_DIR}" ] ; then
        cp -Lr ${CLONED_DIR}/tinker build
      else
        cp -Lr tinker build
      fi
  artifacts:
    paths:
      - build/
    expire_in: 1 day
  rules: !reference [.compile-jobs, rules]
  needs:
    - !reference [.use-clone]

# Define the actual jobs, each job has a "build" and a "test" stage,
# the latter depends on the former.

build:intel:
  extends:
    - .compile
    - .intel
test:intel:
  extends:
    - .run-tests
    - .intel
  needs:
    - !reference [.use-clone]
    - build:intel
  tags:
    - docker

build:intel13:
  extends:
    - .compile
    - .intel13
test:intel13:
  extends:
    - .run-tests
    - .intel13
  needs:
    - !reference [.use-clone]
    - build:intel13
  tags:
    - docker

build:nag:
  extends:
    - .compile
    - .nag
test:nag:
  extends:
    - .run-tests
    - .nag
  needs:
    - !reference [.use-clone]
    - build:nag
  tags:
    - docker

build:garble:
  extends:
    - .compile
    - .garble
test:garble:
  extends:
    - .run-tests
    - .garble
  needs:
    - !reference [.use-clone]
    - build:garble
    - tinker

build:bounds:
  extends:
    - .compile
    - .bounds
test:bounds:
  extends:
    - .run-tests
    - .bounds
  needs:
    - !reference [.use-clone]
    - build:bounds

build:mpi:
  extends:
    - .compile
    - .mpi
test:mpi:
  extends:
    - .run-tests
    - .mpi
  needs:
    - !reference [.use-clone]
    - build:mpi
